name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Debug Repository Structure
        run: |
          pwd
          ls -la
          find . -maxdepth 3 -type d

      - name: Build Application Images
        working-directory: ./app
        run: |
          docker compose build

      - name: Deploy Application
        working-directory: ./app
        run: |
          docker compose down
          docker compose up -d
