name: Security Scan

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  security-scan:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # =========================
      # TruffleHog Report
      # =========================

      - name: TruffleHog Scan
        run: |
          docker run --rm \
            -v "$PWD:/pwd" \
            trufflesecurity/trufflehog:latest filesystem /pwd \
            --json > trufflehog-report.json || true

      - name: Upload TruffleHog Report
        uses: actions/upload-artifact@v4
        with:
          name: trufflehog-report
          path: trufflehog-report.json

      # =========================
      # Bandit Report
      # =========================

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Bandit
        run: |
          pip install bandit

      - name: Run Bandit
        run: |
          bandit \
            -r ./app/backend \
            -f json \
            -o bandit-report.json || true

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit-report.json

      # =========================
      # Hadolint Reports
      # =========================

      - name: Download Hadolint
        run: |
          curl -L \
          https://github.com/hadolint/hadolint/releases/latest
